run_unit_tests doesn't exit on first failure

diff --git a/run_unit_tests b/run_unit_tests
--- a/run_unit_tests
+++ b/run_unit_tests
@@ -3,19 +3,35 @@
 set -e
 tmpdir=$(mktemp -d -p /run/user/$UID upscaledb_testing.XXXXXX)
 
-success=0
+RED="$(tput setaf 1)"
+GREEN="$(tput setaf 2)"
+WHITE="$(tput setaf 7)"
+all_tests_were_run=0
+failure_count=0
 cleanup()
 {
-    if [ "$success" -eq 1 ]
+    if [ "$all_tests_were_run" -ne 1 ]
     then
-        echo "$(tput setaf 2)========== OK ============$(tput setaf 7)"
+        echo "$RED### NOT ALL TESTS WERE RUN ####$WHITE"
+    elif (( failure_count != 0 ))
+    then
+        echo "$RED### There were $failure_count failures ####$WHITE"
     else
-        echo "$(tput setaf 1)########### ERROR #############$(tput setaf 7)"
+        echo "$GREEN========== OK ============$WHITE"
     fi
     rm -rf "$tmpdir"
 }
 
 trap cleanup EXIT
+
+run_test()
+{
+    echo "$*"
+    if ! "$@"
+    then
+        let ++failure_count
+    fi
+}
 
 mydir="$(dirname "$0")"
 mydir="$(cd "$mydir"; pwd)"
@@ -24,15 +40,14 @@ make plugin
 make
 cp -r test issue{32,43,101,105} plugin.so data Makefile.am "$tmpdir"
 cd "$tmpdir"
-(set -x
-./test
-./issue32 -i
-./issue32 -r
-./issue43
-./issue101
+
+run_test ./test
+run_test ./issue32 -i
+run_test ./issue32 -r
+run_test ./issue43
+run_test ./issue101
 for i in {1..10} {45..55} {70..80}
 do
-    ./issue105 "$i"
+    run_test ./issue105 "$i"
 done
-)
-success=1
+all_tests_were_run=1
